name: E2E NG Universal Express on PR
on: pull_request
jobs:
  build_and_ng-universal-express:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Production build for static file hosting (client + prerender)
        run: npm run nx run ng-universal-express:user-flow:production -- --format=md

      - name: Test ng-universal-express
        id: firebase-preview-channel-hosting
        uses: push-based/user-flow-gh-action@v0.4.1
        with:
          verbose: on
          commentId: ng-universal-express
          onlyComments: on
          outPath: ./dist/user-flow/ng-universal-express
          rcPath: ./projects/ng-universal-express/.user-flowrc.json
